# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: ["main"]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    env:
      platform: aws
      region: us-east-1
      account: 1234567890
      
      username: ${{secrets.USERNAME}}
      password: ${{secrets.PASSWORD}}

    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: "Display a Message"
        run: echo "Hola mundo"

      - name: "Show all the environment variables"
        run: |
          echo "This is the value of platform: ${{env.platform}}"
          echo "This is the value of region: ${{env.region}}"
          echo "This is the value of account: ${{env.account}}"

          echo "This is the value of username: ${{env.username}}"
          echo "This is the value of password: ${{env.password}}"

      - name: "Show default variables"
        run: |
          echo "Event: ${{toJSON(github.event)}}"
          echo "GITHUB_ACTOR: $GITHUB_ACTOR"
          echo "GITHUB_REPOSITORY: $GITHUB_REPOSITORY"
